--
-- F_GET_CODE_NM2  (Function) 
--
CREATE OR REPLACE FUNCTION         F_GET_CODE_NM2 (
    P_CODE VARCHAR2
    )
       RETURN VARCHAR2
IS
V_CODE_NM VARCHAR2(100);
BEGIN

SELECT CODE_NM INTO  V_CODE_NM
FROM TB_CODE 
WHERE CODE  = P_CODE
AND ROWNUM =1; 
 RETURN V_CODE_NM;
END;
/
